added a comment
edson-pro/gym-bem-medicore pull request #1
Opened 2022-09-14 11:29 UTC by edson-pro

2022-09-14 11:30 UTC, Jonath-z requested changes
kindly apply the changes

2022-09-14 11:30 UTC, Jonath-z commented on main.css
> +/* // added a chenge */
add a code instead of comment

2022-09-19 06:22 UTC, Jonath-z requested changes
I don't see any modifier in css. kindly add the those modifier

2026-06-13 13:01 UTC, closed without merging

2026-06-23 15:03 UTC, ritha-kankindi commented
I've been attacked by PolinRider

On Sat, Jun 13, 2026 at 3:02 PM Kankindi Ritha Veneranda <
***@***.***> wrote:

> Closed #1 <https://github.com/edson-pro/gym-bem-medicore/pull/1>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/edson-pro/gym-bem-medicore/pull/1?email_source=notifications&email_token=AMSEEZ5TCX5RLXZ6Y5FIH7D47VGFDA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTENRXGA4DSNJYG4ZDNJTSMVQXG33OVV4W65LSL5QWG5DJOZUXI6NFMV3GK3TUVRTG633UMVZF6Y3MNFRWW#event-26708958726>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMSEEZ5UUCXXZEIHXXJPGDL47VGFDAVCNFSNUABFKJSXA33TNF2G64TZHM2TGNRVGQZTCNBTHNEXG43VMU5TCMZXGI4DENJUGY22C5QC>
> .
> Triage notifications, keep track of coding agent tasks and review pull
> requests on the go with GitHub Mobile for iOS
> <https://github.com/notifications/mobile/ios/AMSEEZ7AO3GJQ4YTT27LESL47VGFDA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTENRXGA4DSNJYG4ZDNJTSMVQXG33OVV4W65LSL5QWG5DJOZUXI6NFMV3GK3TUVJTG633UMVZF62LPOM>
> and Android
> <https://github.com/notifications/mobile/android/AMSEEZ2JXTSA45NIOUGTIMD47VGFDA5CNFSNUABQM5UWIORPF5TWS5BNNB2WEL2JONZXKZKFOZSW45CON52GSZTJMNQXI2LPNYXTENRXGA4DSNJYG4ZDNJTSMVQXG33OVV4W65LSL5QWG5DJOZUXI6NFMV3GK3TUVZTG633UMVZF6YLOMRZG62LE>.
> Download it today!
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>